# Generated by Django 3.2.12 on 2022-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=200)),
                ('userEMail', models.CharField(default='', max_length=200)),
                ('userPassword', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
